services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: rec-int

    volumes:
      - type: volume
        source: recdata #creates a named volume for the data to persist even if the container gets deleted
        target: /var/lib/postgresql/data
        
    healthcheck: #checks if the database is accepting connections
      test: ['CMD-SHELL', 'pg_isready -U user -d rec-int']
      interval: 5s
      retries: 5

  app:
      build: . #looks for dockerfile in root folder
      environment:
        PROJECT_NAME: ${PROJECT_NAME}
        DATABASE_URL: postgresql://user:pwd@db:5432/rec-int
        TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
        GOOGLE_APPLICATION_CREDENTIALS: /secrets/key.json

      volumes:
      - type: bind
        source: ./receipt-interepreter-497814-a4d3d8116b75.json #bind mount linking local file containing google vertex ai authentication to the container
        target: /secrets/key.json
        read_only: true

      depends_on: #makes sure that the app only starts after the db service
        db: 
          condition: service_healthy

volumes: #all named volumes must be declared at this level
  recdata: